#!/bin/sh

echo "Checking status of mygpiod system user and group"
getent group gpio > /dev/null ||  groupadd -r gpio
getent passwd mygpiod > /dev/null || useradd -r -g gpio -s /bin/false -d /var/lib/mygpiod mygpiod

echo "myGPIOd installed"
echo "Modify /etc/mygpiod.conf to suit your needs."
exit 0
