.\" Manpage for mygpiod.
.\" Contact <mail@jcgames.de> to correct errors or typos.
.TH man 1 "17 Dec 2023" "0.4.0" "mygpiod man page"

.SH NAME
myGPIOd \- lightweight gpio controlling daemon

.SH SYNOPSIS
mygpiod [/etc/mygpiod.conf]

.SH DESCRIPTION
myGPIOd is a very lightweight daemon to control gpio devices.

.SH AUTHOR
Juergen Mang (mail@jcgames.de)

.SH BUGS
If you find a bug, please report it at https://github.com/jcorporation/myGPIOd/issues

.SH SEE ALSO
https://github.com/jcorporation/myGPIOd
