.TH "libmygpio/include/libmygpio/libmygpio_protocol.h" 3 "libmygpio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmygpio/include/libmygpio/libmygpio_protocol.h \- myGPIOd client library  

.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBmygpio_response_end\fP (struct \fBt_mygpio_connection\fP *connection)"
.br
.in -1c
.SH "Detailed Description"
.PP 
myGPIOd client library 

Do not include this header directly\&. Use \fBlibmygpio/libmygpio\&.h\fP instead\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libmygpio from the source code\&.
