.TH "libmygpio/include/libmygpio/libmygpio_gpioinfo.h" 3 "Sun Dec 24 2023" "libmygpio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmygpio/include/libmygpio/libmygpio_gpioinfo.h \- myGPIOd client library  

.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBmygpio_gpioinfo\fP (struct \fBt_mygpio_connection\fP *connection, unsigned gpio)"
.br
.ti -1c
.RI "struct \fBt_mygpio_gpio\fP * \fBmygpio_recv_gpio_info\fP (struct \fBt_mygpio_connection\fP *connection)"
.br
.in -1c
.SH "Detailed Description"
.PP 
myGPIOd client library 

Do not include this header directly\&. Use \fBlibmygpio/libmygpio\&.h\fP instead\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libmygpio from the source code\&.
