.TH "libmygpio_gpioinfo" 3 "libmygpio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmygpio_gpioinfo \- GPIO info
.PP
 \- This module provides functions for the gpioinfo protocol command\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBmygpio_gpioinfo\fP (struct \fBt_mygpio_connection\fP *connection, unsigned gpio)"
.br
.ti -1c
.RI "struct \fBt_mygpio_gpio\fP * \fBmygpio_recv_gpio_info\fP (struct \fBt_mygpio_connection\fP *connection)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This module provides functions for the gpioinfo protocol command\&. 


.SH "Function Documentation"
.PP 
.SS "bool mygpio_gpioinfo (struct \fBt_mygpio_connection\fP * connection, unsigned gpio)"
Lists the current settings of a GPIO\&. Retrieve the settings with mygpio_recv_gpio_info and end the response with mygpio_response_end\&. 
.PP
\fBParameters\fP
.RS 4
\fIconnection\fP Pointer to the connection struct returned by mygpio_connection_new\&. 
.br
\fIgpio\fP GPIO number 
.RE
.PP
\fBReturns\fP
.RS 4
bool true on success, else false\&. 
.RE
.PP

.SS "struct \fBt_mygpio_gpio\fP * mygpio_recv_gpio_info (struct \fBt_mygpio_connection\fP * connection)"
Receives the result of mygpio_gpioinfo\&. Free it with mygpio_free_gpio\&. Use the mygpio_gpio_get_gpio_*, mygpio_gpio_in_get_gpio_* and mygpio_gpio_in_get_gpio_* functions to access the values\&. The caller must free it with mygpio_free_gpio\&. 
.PP
\fBParameters\fP
.RS 4
\fIconnection\fP Pointer to the connection struct returned by mygpio_connection_new\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Allocated struct \fBt_mygpio_gpio\fP or NULL on list end or error\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libmygpio from the source code\&.
