.TH "t_mygpio_connection" 3 "Mon Dec 18 2023" "libmygpio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_mygpio_connection
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libmygpio_connection\&.h>\fP
.SH "Detailed Description"
.PP 
The opaque myGPIOd connection object\&. You can not access it directly\&. Refer to \fBmyGPIOd connection\fP for function that operate on this struct\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libmygpio from the source code\&.
