.TH "t_mygpio_idle_event" 3 "Wed Dec 20 2023" "libmygpio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_mygpio_idle_event
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libmygpio_idle\&.h>\fP
.SH "Detailed Description"
.PP 
The opaque myGPIOd idle event object\&. You can not access it directly\&. Refer to \fBIdle events\fP for function that operate on this struct\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libmygpio from the source code\&.
